### PR TITLE
Changes to use dependencies from @openzeppelin/contracts instead of forking the contracts

### PR DESCRIPTION
**Pull request by ayobuenavista**
This means removing contracts/zeppelin.

In `Utils.sol`, ERC20.sol needed to be used instead of IERC20.sol, since decimals() is an optional property of the standard and is not included in the IERC20.sol interface. See: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md

### CODE REVIEW

**Review by ducquangkstn — DISMISSED** [review]

**Review by Anyhowclick — DISMISSED** [review]

**Comment by ilanDoron** [comment]
> ce decimals() is an optional property of the standard and is not included in the IERC20.sol interface. See: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md

BTW
We can add decimals to IERC20 as well.
I mean.
this is not the reason.
is it?

**Review by ilanDoron — DISMISSED** [review]

**Comment by ayobuenavista** [comment]
> > ce decimals() is an optional property of the standard and is not included in the IERC20.sol interface. See: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md
> 
> BTW
> We can add decimals to IERC20 as well.
> I mean.
> this is not the reason.
> is it?

Yes, we can add, but we will fork it which is what we did previously. But in the standard it says, `This method can be used to improve usability, but interfaces and other contracts MUST NOT expect these values to be present.` So I guess there are contracts out there that haven't implemented decimals.

**Review by Anyhowclick — DISMISSED** [review]

**Comment by ayobuenavista** [comment]
Things to note here:

1) We have removed the zeppelin folder, thus removing Address, SafeERC20, SafeMath, and ReentrancyGuard. Please use these contracts from the official `@openzeppelin/contracts` NPM package instead.
2) The only thing missing from SafeERC20 from ours compared to @openzeppelin is that min() is no longer there. But it seems like it's not used anywhere in reserves, except for one instance in KyberStaking.
3) The original IERC20 interface from @openzeppelin doesn't have decimals(). So we've extended it and added it, creating our interface IERC20Ext (IERC20 extended).

**Review by ilanDoron — DISMISSED** [review]

**Review by ilanDoron — COMMENTED** [review]
please merge when npm deploy process is done.

**Review by ilanDoron — APPROVED** [review]

**Review by Anyhowclick — APPROVED** [review]

**Pull request merged**
